const fs = require('fs');
let c = fs.readFileSync('src/app/admin/live-data/LiveDataClient.tsx', 'utf8');

c = c.replace(
  'const pipelineDeals = activeDeals.filter(d => {\n      if (![\'C\', \'D\', \'E\'].includes(d.status)) return false;',
  'const pipelineDeals = activeDeals.filter(d => {\n      const allowed = [\'C\', \'D\', \'E\'];\n      if (showPipelineTender) allowed.push(\'T\');\n      if (showPipelineHold) allowed.push(\'H\');\n      if (!allowed.includes(d.status)) return false;'
);

c = c.replace(
  '<h3 style={{ fontSize: 12, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.1em", color: "#676879" }}>Pipeline Status Funnel</h3>\n              </div>\n              <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>\n                {["E", "D", "C", "B", "A"]\n                  .map((status) => {',
  '<h3 style={{ fontSize: 12, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.1em", color: "#676879" }}>Pipeline Status Funnel</h3>\n              </div>\n              <div style={{ display: "flex", gap: 12, marginBottom: 12 }}>\n                  <label style={{ display: "flex", alignItems: "center", gap: 6, cursor: "pointer" }}>\n                    <div style={{ position: "relative", width: 28, height: 16, background: showPipelineTender ? "#e44258" : "#cbd5e1", borderRadius: 16, transition: "0.3s" }}>\n                      <div style={{ position: "absolute", top: 2, left: showPipelineTender ? 14 : 2, width: 12, height: 12, background: "white", borderRadius: "50%", transition: "0.3s" }} />\n                    </div>\n                    <input type="checkbox" checked={showPipelineTender} onChange={(e) => setShowPipelineTender(e.target.checked)} style={{ display: "none" }} />\n                    <span style={{ fontSize: 10, fontWeight: 600, color: "#64748b" }}>Eng. Review</span>\n                  </label>\n                  <label style={{ display: "flex", alignItems: "center", gap: 6, cursor: "pointer" }}>\n                    <div style={{ position: "relative", width: 28, height: 16, background: showPipelineHold ? "#8d949e" : "#cbd5e1", borderRadius: 16, transition: "0.3s" }}>\n                      <div style={{ position: "absolute", top: 2, left: showPipelineHold ? 14 : 2, width: 12, height: 12, background: "white", borderRadius: "50%", transition: "0.3s" }} />\n                    </div>\n                    <input type="checkbox" checked={showPipelineHold} onChange={(e) => setShowPipelineHold(e.target.checked)} style={{ display: "none" }} />\n                    <span style={{ fontSize: 10, fontWeight: 600, color: "#64748b" }}>Hold</span>\n                  </label>\n                </div>\n              <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>\n                {(showPipelineHold ? ["H"] : []).concat(showPipelineTender ? ["T"] : []).concat(["E", "D", "C", "B", "A"])\n                  .map((status) => {'
);

fs.writeFileSync('src/app/admin/live-data/LiveDataClient.tsx', c);
